name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build qpdfview
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set edition
        run: |
          QPDFVIEW_EDITION=$(git rev-list --count --first-parent HEAD)
          echo "QPDFVIEW_EDITION=${QPDFVIEW_EDITION}" >> "$GITHUB_ENV"

      - name: Add brew repo with poppler-qt6
        run: brew tap muzimuzhi/homebrew-poppler-build

      - name: Update brew
        run: brew update

      - name: Install dependencies
        # Ignore random brew failures.
        run: brew install qt mupdf-tools mujs lcms2 libspectre freetype harfbuzz djvulibre lcms2 create-dmg || true

      - name: Install poppler-qt6 from source
        run: brew install poppler-qt6 -s

      - name: Install launchpadlib
        run: python3 -m pip install breezy launchpadlib

      - name: Activate mupdf
        run: |
          FITZ_PLUGIN_INCLUDEPATH=$(brew --prefix mupdf-tools)/include
          echo "FITZ_PLUGIN_INCLUDEPATH=${FITZ_PLUGIN_INCLUDEPATH}" >> "$GITHUB_ENV"
          FITZ_PLUGIN_LINKPATH=$(brew --prefix mupdf-tools)/lib
          echo "FITZ_PLUGIN_LINKPATH=${FITZ_PLUGIN_LINKPATH}" >> "$GITHUB_ENV"
          FITZ_PLUGIN_LIBS="-lmupdf -lmupdf-third -L$(brew --prefix mujs)/lib -lmujs -L$(brew --prefix freetype)/lib -lfreetype -L$(brew --prefix harfbuzz)/lib -lharfbuzz -lz -L$(brew --prefix jpeg)/lib -ljpeg -L$(brew --prefix jbig2dec)/lib -ljbig2dec -L$(brew --prefix openjpeg)/lib -lopenjp2 -L$(brew --prefix lcms2)/lib -llcms2" 
          echo "FITZ_PLUGIN_LIBS=${FITZ_PLUGIN_LIBS}" >> "$GITHUB_ENV"

      - name: Compile with codesign
        if: github.repository_owner == 'vit9696'
        env:
          MAC_CERTIFICATE_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
          MAC_ACCOUNT_NAME: ${{ secrets.MAC_ACCOUNT_NAME }}
          MAC_ACCOUNT_PASSWORD: ${{ secrets.MAC_ACCOUNT_PASSWORD }}
        run: |
          curl -OL "https://github.com/acidanthera/ocbuild/raw/master/codesign/appsign.sh" || exit 1
          chmod a+x appsign.sh || exit 1
          DEPLOY_SCRIPT="$(pwd)/appsign.sh" ./qpdfview.sh

      - name: Compile without codesign
        if: github.repository_owner != 'vit9696'
        run: ./qpdfview.sh

      - name: Create release notes
        run: git show -s --format="%s" > release_notes.md

      - name: Create release
        if: github.repository_owner == 'vit9696'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.REVISION }}
          release_name: qpdfview ${{ env.VERSION }} (${{ env.REVISION }})
          body_path: release_notes.md
          draft: false
          prerelease: false

      - name: Upload release
        if: github.repository_owner == 'vit9696'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.FILENAME }}
          asset_name: ${{ env.FILENAME }}
          asset_content_type: ${{ env.CONTENT_TYPE }}
